import { Employee } from './types';

export const INITIAL_DATA: Employee[] = [
  {
    "id": "1",
    "sequenceNumber": 1,
    "code": "1008",
    "jobTitle": "العضو المنتدب",
    "name": "نايف محمد عبدالله الخضره",
    "branch": "الادارة",
    "hireDate": "2020-08-01",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 20000,
    "housingAllowance": 5000,
    "transferAllowance": 2000,
    "phoneAllowance": 300,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 2500,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "2",
    "sequenceNumber": 2,
    "code": "1010",
    "jobTitle": "نائب المدير العام",
    "name": "محمد أحمد محمد البدري",
    "branch": "الادارة",
    "hireDate": "2013-02-02",
    "lastVacationReturnDate": "2025-07-27",
    "calculationDate": "2026-12-31",
    "basicSalary": 19000,
    "housingAllowance": 4750,
    "transferAllowance": 1900,
    "phoneAllowance": 200,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 1500,
    "paidEndOfService": 250000,
    "socialSecurity": 2375,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "3",
    "sequenceNumber": 3,
    "code": "1005",
    "jobTitle": "مدير المشتريات",
    "name": "معتز حامد صالح الشوربجي",
    "branch": "الادارة",
    "hireDate": "2015-02-07",
    "lastVacationReturnDate": "2025-07-06",
    "calculationDate": "2026-12-31",
    "basicSalary": 7700,
    "housingAllowance": 1925,
    "transferAllowance": 700,
    "phoneAllowance": 100,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 1500,
    "paidEndOfService": 50000,
    "socialSecurity": 962.5,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "4",
    "sequenceNumber": 4,
    "code": "1046",
    "jobTitle": "مدير الحسابات",
    "name": "علاء أحمد عنتر المرشدي",
    "branch": "الادارة",
    "hireDate": "2008-08-01",
    "lastVacationReturnDate": "2025-04-19",
    "calculationDate": "2026-12-31",
    "basicSalary": 5500,
    "housingAllowance": 1375,
    "transferAllowance": 0,
    "phoneAllowance": 60,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 1500,
    "paidEndOfService": 65000,
    "socialSecurity": 687.5,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "5",
    "sequenceNumber": 5,
    "code": "1006",
    "jobTitle": "معقب",
    "name": "علي محمد منصور الخلف",
    "branch": "الادارة",
    "hireDate": "2005-12-26",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 5000,
    "housingAllowance": 1250,
    "transferAllowance": 0,
    "phoneAllowance": 60,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 625,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "6",
    "sequenceNumber": 6,
    "code": "1143",
    "jobTitle": "امين صندوق",
    "name": "ابراهيم اسماعيل الحمادي",
    "branch": "الادارة",
    "hireDate": "2020-03-01",
    "lastVacationReturnDate": "2025-06-11",
    "calculationDate": "2026-12-31",
    "basicSalary": 3500,
    "housingAllowance": 583,
    "transferAllowance": 500,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 408.3,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "7",
    "sequenceNumber": 7,
    "code": "1030",
    "jobTitle": "مندوبة مبيعات",
    "name": "أروى إبراهيم الشامسي",
    "branch": "الادارة",
    "hireDate": "2022-02-01",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 4000,
    "housingAllowance": 500,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 450,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "8",
    "sequenceNumber": 8,
    "code": "1145",
    "jobTitle": "مندوبة مبيعات",
    "name": "عبير محمد بن مبارك الدوسري",
    "branch": "الادارة",
    "hireDate": "2021-04-01",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 4000,
    "housingAllowance": 500,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 450,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "9",
    "sequenceNumber": 9,
    "code": "1161",
    "jobTitle": "محاسبة مبيعات",
    "name": "عهد تركي فهد الدوسري",
    "branch": "الادارة",
    "hireDate": "2023-04-13",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 4500,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 450,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "10",
    "sequenceNumber": 10,
    "code": "1151",
    "jobTitle": "أمين مستودع",
    "name": "فضيله محمد منصور الخلف",
    "branch": "الادارة",
    "hireDate": "2022-09-01",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 4000,
    "housingAllowance": 500,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 450,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "11",
    "sequenceNumber": 11,
    "code": "1177",
    "isActive": false,
    "jobTitle": "اخصائي معمل",
    "name": "اماني إبراهيم يحي الفيفي",
    "branch": "الادارة",
    "hireDate": "2025-05-24",
    "lastVacationReturnDate": "2026-05-31",
    "calculationDate": "2026-05-31",
    "basicSalary": 4500,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 450,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "12",
    "sequenceNumber": 12,
    "code": "1180",
    "jobTitle": "محاسبة مبيعات",
    "name": "مشاعل موسى ابراهيم بكاري",
    "branch": "الادارة",
    "hireDate": "2025-09-14",
    "lastVacationReturnDate": "2025-09-14",
    "calculationDate": "2026-12-31",
    "basicSalary": 4500,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 450,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "13",
    "sequenceNumber": 13,
    "code": "1185",
    "jobTitle": "كيميائية",
    "name": "باسمه محمد حسين الهاشم",
    "branch": "الادارة",
    "hireDate": "2021-01-01",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 4500,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 450,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "14",
    "sequenceNumber": 14,
    "code": "1186",
    "jobTitle": "مندوبة مبيعات",
    "name": "لولوه شافي بن سيف المنصوري",
    "branch": "الادارة",
    "hireDate": "2021-01-01",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 4000,
    "housingAllowance": 500,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 0,
    "paidEndOfService": 0,
    "socialSecurity": 450,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "15",
    "sequenceNumber": 15,
    "code": "1158",
    "jobTitle": "ميكانيكي",
    "name": "صغير احمد بحر خان",
    "branch": "المركز الرئيسي",
    "hireDate": "2023-02-19",
    "lastVacationReturnDate": "2025-07-08",
    "calculationDate": "2026-12-31",
    "basicSalary": 1700,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 200,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 170,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "16",
    "sequenceNumber": 16,
    "code": "1056",
    "jobTitle": "مبيعات",
    "name": "عبد الرحمن شهاب الدين",
    "branch": "المركز الرئيسي",
    "hireDate": "1991-01-01",
    "lastVacationReturnDate": "2025-08-16",
    "calculationDate": "2026-12-31",
    "basicSalary": 2600,
    "housingAllowance": 650,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 95000,
    "socialSecurity": 325,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "17",
    "sequenceNumber": 17,
    "code": "1102",
    "jobTitle": "سائق",
    "name": "كاجي بهادور غالي كمال",
    "branch": "المركز الرئيسي",
    "hireDate": "2010-06-24",
    "lastVacationReturnDate": "2026-05-13",
    "calculationDate": "2026-12-31",
    "basicSalary": 1500,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1750,
    "paidEndOfService": 10000,
    "socialSecurity": 150,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "18",
    "sequenceNumber": 18,
    "code": "1104",
    "jobTitle": "مبيعات",
    "name": "محمد كمال حسين",
    "branch": "المركز الرئيسي",
    "hireDate": "2020-11-01",
    "lastVacationReturnDate": "2025-04-13",
    "calculationDate": "2026-12-31",
    "basicSalary": 1800,
    "housingAllowance": 167,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 2000,
    "paidEndOfService": 0,
    "socialSecurity": 196.7,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "19",
    "sequenceNumber": 19,
    "code": "1097",
    "jobTitle": "مشغل",
    "name": "جيمي هاو قرقاريو",
    "branch": "المركز الرئيسي",
    "hireDate": "2014-02-04",
    "lastVacationReturnDate": "2024-10-08",
    "calculationDate": "2026-12-31",
    "basicSalary": 2050,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 200,
    "fixedAllowances": 0,
    "ticketPrice": 2700,
    "paidEndOfService": 12000,
    "socialSecurity": 205,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "20",
    "sequenceNumber": 20,
    "code": "1171",
    "jobTitle": "مشغل",
    "name": "ماجومادار سويكوت",
    "branch": "المركز الرئيسي",
    "hireDate": "2024-12-26",
    "lastVacationReturnDate": "2024-12-26",
    "calculationDate": "2026-12-31",
    "basicSalary": 1600,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 200,
    "fixedAllowances": 0,
    "ticketPrice": 2000,
    "paidEndOfService": 0,
    "socialSecurity": 160,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "21",
    "sequenceNumber": 21,
    "code": "1184",
    "jobTitle": "مشغل",
    "name": "محيبر الرحمن الرحمن محيبر",
    "branch": "المركز الرئيسي",
    "hireDate": "2021-01-01",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 200,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "22",
    "sequenceNumber": 22,
    "code": "1060",
    "jobTitle": "سائق",
    "name": "سانتراج كاتوار يادف",
    "branch": "المركز الرئيسي",
    "hireDate": "2016-05-14",
    "lastVacationReturnDate": "2026-04-19",
    "calculationDate": "2026-12-31",
    "basicSalary": 1600,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 2000,
    "socialSecurity": 160,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "23",
    "sequenceNumber": 23,
    "code": "1091",
    "jobTitle": "سائق",
    "name": "جومير جاراسيا",
    "branch": "المركز الرئيسي",
    "hireDate": "1997-11-21",
    "lastVacationReturnDate": "2024-01-25",
    "calculationDate": "2026-12-31",
    "basicSalary": 2000,
    "housingAllowance": 300,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 200,
    "fixedAllowances": 0,
    "ticketPrice": 2700,
    "paidEndOfService": 17000,
    "socialSecurity": 230,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "24",
    "sequenceNumber": 24,
    "code": "1093",
    "jobTitle": "سائق",
    "name": "ماني فانيلبيو سلونا",
    "branch": "المركز الرئيسي",
    "hireDate": "2005-06-05",
    "lastVacationReturnDate": "2026-01-29",
    "calculationDate": "2026-12-31",
    "basicSalary": 1850,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 200,
    "fixedAllowances": 0,
    "ticketPrice": 2700,
    "paidEndOfService": 8000,
    "socialSecurity": 185,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "25",
    "sequenceNumber": 25,
    "code": "1108",
    "jobTitle": "سائق",
    "name": "نزرو الحسين علي حسين",
    "branch": "المركز الرئيسي",
    "hireDate": "2002-05-13",
    "lastVacationReturnDate": "2025-05-06",
    "calculationDate": "2026-12-31",
    "basicSalary": 1800,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 2000,
    "paidEndOfService": 25000,
    "socialSecurity": 180,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "26",
    "sequenceNumber": 26,
    "code": "1109",
    "jobTitle": "سائق",
    "name": "كمال الدين شمس الحق",
    "branch": "المركز الرئيسي",
    "hireDate": "2001-07-09",
    "lastVacationReturnDate": "2022-03-15",
    "calculationDate": "2026-12-31",
    "basicSalary": 1500,
    "housingAllowance": 167,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 2000,
    "paidEndOfService": 10000,
    "socialSecurity": 166.7,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "27",
    "sequenceNumber": 27,
    "code": "1155",
    "jobTitle": "سائق",
    "name": "مهيم الدين الله سناء",
    "branch": "المركز الرئيسي",
    "hireDate": "2023-01-10",
    "lastVacationReturnDate": "2023-01-10",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 2000,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "28",
    "sequenceNumber": 28,
    "code": "1156",
    "jobTitle": "سائق",
    "name": "دينيش كومار",
    "branch": "المركز الرئيسي",
    "hireDate": "2023-01-10",
    "lastVacationReturnDate": "2023-01-10",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "29",
    "sequenceNumber": 29,
    "code": "1163",
    "jobTitle": "سائق",
    "name": "امتياز احمد",
    "branch": "المركز الرئيسي",
    "hireDate": "2024-01-01",
    "lastVacationReturnDate": "2026-01-29",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "30",
    "sequenceNumber": 30,
    "code": "1169",
    "jobTitle": "سائق",
    "name": "مشرف حسين",
    "branch": "المركز الرئيسي",
    "hireDate": "2024-09-22",
    "lastVacationReturnDate": "2024-09-22",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "31",
    "sequenceNumber": 31,
    "code": "1168",
    "jobTitle": "سائق شاحنة ثقيلة",
    "name": "سوريش كومار",
    "branch": "المركز الرئيسي",
    "hireDate": "2024-09-03",
    "lastVacationReturnDate": "2024-09-03",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 300,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "32",
    "sequenceNumber": 32,
    "code": "1170",
    "jobTitle": "سائق",
    "name": "سلمان مومين",
    "branch": "المركز الرئيسي",
    "hireDate": "2024-10-08",
    "lastVacationReturnDate": "2024-10-08",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "33",
    "sequenceNumber": 33,
    "code": "1173",
    "jobTitle": "سائق",
    "name": "مصيد الرحمان عبد الرحمن",
    "branch": "المركز الرئيسي",
    "hireDate": "2025-03-27",
    "lastVacationReturnDate": "2025-03-27",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "34",
    "sequenceNumber": 34,
    "code": "1183",
    "jobTitle": "سائق",
    "name": "محبندر سينغ راكور",
    "branch": "المركز الرئيسي",
    "hireDate": "2021-01-01",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "35",
    "sequenceNumber": 35,
    "code": "1181",
    "jobTitle": "ميكانيكي",
    "name": "محمد رياض",
    "branch": "المركز الرئيسي",
    "hireDate": "2025-10-29",
    "lastVacationReturnDate": "2025-10-29",
    "calculationDate": "2026-12-31",
    "basicSalary": 1200,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 120,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "36",
    "sequenceNumber": 36,
    "code": "1178",
    "jobTitle": "سائق شاحنة ثقيلة",
    "name": "عبد الصمد عبد السلام",
    "branch": "المركز الرئيسي",
    "hireDate": "2025-08-02",
    "lastVacationReturnDate": "2025-08-02",
    "calculationDate": "2026-07-02",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 300,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "37",
    "sequenceNumber": 37,
    "code": "1179",
    "jobTitle": "سائق شاحنة ثقيلة",
    "branch": "المركز الرئيسي",
    "hireDate": "2025-08-05",
    "lastVacationReturnDate": "2025-08-05",
    "calculationDate": "2026-07-02",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 300,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": "",
    "name": "صاحب جود"
  },
  {
    "id": "38",
    "sequenceNumber": 38,
    "code": "1154",
    "jobTitle": "عامل",
    "name": "محمد عبد ال مالك",
    "branch": "المركز الرئيسي",
    "hireDate": "2022-12-01",
    "lastVacationReturnDate": "2026-04-20",
    "calculationDate": "2026-12-31",
    "basicSalary": 1200,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 2000,
    "paidEndOfService": 0,
    "socialSecurity": 120,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "39",
    "sequenceNumber": 39,
    "code": "1076",
    "jobTitle": "مبيعات",
    "name": "يس أحمد عبدالجبار البكري",
    "branch": "فرع الدمام",
    "hireDate": "2011-05-09",
    "lastVacationReturnDate": "2024-01-04",
    "calculationDate": "2026-12-31",
    "basicSalary": 3150,
    "housingAllowance": 525,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 1350,
    "paidEndOfService": 37000,
    "socialSecurity": 367.5,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "40",
    "sequenceNumber": 40,
    "code": "1148",
    "jobTitle": "مشغل",
    "name": "محمد سلمان الأنصاري",
    "branch": "المركز الرئيسي",
    "hireDate": "2021-10-06",
    "lastVacationReturnDate": "2026-04-12",
    "calculationDate": "2026-12-31",
    "basicSalary": 2000,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 200,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 200,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "41",
    "sequenceNumber": 41,
    "code": "1067",
    "jobTitle": "سائق",
    "name": "صقري يداف",
    "branch": "فرع الاحساء",
    "hireDate": "2014-12-10",
    "lastVacationReturnDate": "2025-10-21",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 5000,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "42",
    "sequenceNumber": 42,
    "code": "1057",
    "jobTitle": "مشغل",
    "name": "محمد طارق أنس أحمد",
    "branch": "فرع الدمام",
    "hireDate": "2013-04-22",
    "lastVacationReturnDate": "2025-11-12",
    "calculationDate": "2026-12-31",
    "basicSalary": 1600,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 200,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 4000,
    "socialSecurity": 160,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "43",
    "sequenceNumber": 43,
    "code": "1157",
    "jobTitle": "سائق",
    "name": "هاربال سينغ بوكشتين سينغ",
    "branch": "المركز الرئيسي",
    "hireDate": "2023-01-10",
    "lastVacationReturnDate": "2025-03-29",
    "calculationDate": "2026-12-31",
    "basicSalary": 1400,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 140,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "44",
    "sequenceNumber": 44,
    "code": "1159",
    "jobTitle": "عامل",
    "name": "محمد نظيم",
    "branch": "فرع المعباه",
    "hireDate": "2023-02-26",
    "lastVacationReturnDate": "2025-07-02",
    "calculationDate": "2026-12-31",
    "basicSalary": 1000,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 100,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "45",
    "sequenceNumber": 45,
    "code": "1160",
    "jobTitle": "عامل",
    "name": "محمد شاهباز خان",
    "branch": "فرع المعباه",
    "hireDate": "2023-02-26",
    "lastVacationReturnDate": "2026-01-01",
    "calculationDate": "2026-12-31",
    "basicSalary": 1000,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 100,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "46",
    "sequenceNumber": 46,
    "code": "1175",
    "jobTitle": "عامل",
    "name": "محمد سليم",
    "branch": "المركز الرئيسي",
    "hireDate": "2021-01-01",
    "lastVacationReturnDate": "2025-12-31",
    "calculationDate": "2026-12-31",
    "basicSalary": 1000,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 300,
    "fixedAllowances": 0,
    "ticketPrice": 1650,
    "paidEndOfService": 0,
    "socialSecurity": 100,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "47",
    "sequenceNumber": 47,
    "code": "1078",
    "jobTitle": "مبيعات",
    "name": "الترابى أحمد أدريس على",
    "branch": "فرع الاحساء",
    "hireDate": "2016-01-20",
    "lastVacationReturnDate": "2026-06-01",
    "calculationDate": "2026-12-31",
    "basicSalary": 1800,
    "housingAllowance": 300,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 0,
    "fixedAllowances": 0,
    "ticketPrice": 1350,
    "paidEndOfService": 5000,
    "socialSecurity": 0,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  },
  {
    "id": "48",
    "sequenceNumber": 48,
    "code": "1147",
    "jobTitle": "مشغل",
    "name": "نعمان كبير حسين",
    "branch": "فرع الاحساء",
    "hireDate": "2021-09-13",
    "lastVacationReturnDate": "2023-11-12",
    "calculationDate": "2026-12-31",
    "basicSalary": 1600,
    "housingAllowance": 0,
    "transferAllowance": 0,
    "phoneAllowance": 0,
    "foodAllowance": 200,
    "fixedAllowances": 0,
    "ticketPrice": 2000,
    "paidEndOfService": 0,
    "socialSecurity": 0,
    "loans": 0,
    "absence": 0,
    "withdrawals": 0,
    "notes": ""
  }
];
